#!/usr/bin/bash
pyuic4 sequential_clearance_mainwindow.ui -o ui_sequential_clearance_mainwindow.py
pyrcc4 sequential_clearance_resources.qrc -o sequential_clearance_resources_rc.qrc
pyrcc4 sequential_clearance_resources2.qrc -o sequential_clearance_resources2_rc.qrc