# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cmoman/git/Sequential_Clearance/sequential_clearance_mainwindow.ui'
#
# Created: Sat Mar 29 23:13:07 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MplMainWindow(object):
    def setupUi(self, MplMainWindow):
        MplMainWindow.setObjectName(_fromUtf8("MplMainWindow"))
        MplMainWindow.resize(819, 643)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MplMainWindow.sizePolicy().hasHeightForWidth())
        MplMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Logo_Export_no_text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MplMainWindow.setWindowIcon(icon)
        self.mplcentralwidget = QtGui.QWidget(MplMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplcentralwidget.sizePolicy().hasHeightForWidth())
        self.mplcentralwidget.setSizePolicy(sizePolicy)
        self.mplcentralwidget.setMinimumSize(QtCore.QSize(600, 400))
        self.mplcentralwidget.setObjectName(_fromUtf8("mplcentralwidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.mplcentralwidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.frame = QtGui.QFrame(self.mplcentralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mplinc_highset_SpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mplinc_highset_SpinBox.setMinimum(2.0)
        self.mplinc_highset_SpinBox.setMaximum(30.0)
        self.mplinc_highset_SpinBox.setProperty("value", 10.0)
        self.mplinc_highset_SpinBox.setObjectName(_fromUtf8("mplinc_highset_SpinBox"))
        self.gridLayout.addWidget(self.mplinc_highset_SpinBox, 6, 1, 1, 1)
        self.mplinc_checkBox = QtGui.QCheckBox(self.frame)
        self.mplinc_checkBox.setObjectName(_fromUtf8("mplinc_checkBox"))
        self.gridLayout.addWidget(self.mplinc_checkBox, 7, 1, 1, 1)
        self.curveComboBox_1 = QtGui.QComboBox(self.frame)
        self.curveComboBox_1.setEditable(False)
        self.curveComboBox_1.setObjectName(_fromUtf8("curveComboBox_1"))
        self.curveComboBox_1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.curveComboBox_1, 4, 1, 1, 1)
        self.mpldoubleSpinBox6 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox6.setDecimals(0)
        self.mpldoubleSpinBox6.setMinimum(200.0)
        self.mpldoubleSpinBox6.setMaximum(4000.0)
        self.mpldoubleSpinBox6.setSingleStep(50.0)
        self.mpldoubleSpinBox6.setProperty("value", 1200.0)
        self.mpldoubleSpinBox6.setObjectName(_fromUtf8("mpldoubleSpinBox6"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox6, 1, 1, 1, 1)
        self.mplfdr1_cbtime_SpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mplfdr1_cbtime_SpinBox.setMaximum(1.0)
        self.mplfdr1_cbtime_SpinBox.setSingleStep(0.01)
        self.mplfdr1_cbtime_SpinBox.setProperty("value", 0.06)
        self.mplfdr1_cbtime_SpinBox.setObjectName(_fromUtf8("mplfdr1_cbtime_SpinBox"))
        self.gridLayout.addWidget(self.mplfdr1_cbtime_SpinBox, 9, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.mpldoubleSpinBox7 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox7.setDecimals(0)
        self.mpldoubleSpinBox7.setMinimum(50.0)
        self.mpldoubleSpinBox7.setMaximum(1200.0)
        self.mpldoubleSpinBox7.setSingleStep(50.0)
        self.mpldoubleSpinBox7.setProperty("value", 400.0)
        self.mpldoubleSpinBox7.setObjectName(_fromUtf8("mpldoubleSpinBox7"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox7, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.mpldoubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox.setMinimum(0.01)
        self.mpldoubleSpinBox.setMaximum(10.0)
        self.mpldoubleSpinBox.setSingleStep(0.05)
        self.mpldoubleSpinBox.setProperty("value", 2.0)
        self.mpldoubleSpinBox.setObjectName(_fromUtf8("mpldoubleSpinBox"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox, 6, 4, 1, 1)
        self.mplfdr2_highset_SpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mplfdr2_highset_SpinBox.setMinimum(2.0)
        self.mplfdr2_highset_SpinBox.setMaximum(30.0)
        self.mplfdr2_highset_SpinBox.setProperty("value", 10.0)
        self.mplfdr2_highset_SpinBox.setObjectName(_fromUtf8("mplfdr2_highset_SpinBox"))
        self.gridLayout.addWidget(self.mplfdr2_highset_SpinBox, 6, 3, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.mplspinBox = QtGui.QSpinBox(self.frame)
        self.mplspinBox.setMinimum(5)
        self.mplspinBox.setMaximum(20)
        self.mplspinBox.setProperty("value", 10)
        self.mplspinBox.setObjectName(_fromUtf8("mplspinBox"))
        self.gridLayout.addWidget(self.mplspinBox, 1, 4, 1, 1)
        self.mpldoubleSpinBox8 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox8.setDecimals(0)
        self.mpldoubleSpinBox8.setMinimum(50.0)
        self.mpldoubleSpinBox8.setMaximum(1200.0)
        self.mpldoubleSpinBox8.setSingleStep(50.0)
        self.mpldoubleSpinBox8.setProperty("value", 400.0)
        self.mpldoubleSpinBox8.setObjectName(_fromUtf8("mpldoubleSpinBox8"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox8, 1, 3, 1, 1)
        self.mplfdr2_checkBox = QtGui.QCheckBox(self.frame)
        self.mplfdr2_checkBox.setObjectName(_fromUtf8("mplfdr2_checkBox"))
        self.gridLayout.addWidget(self.mplfdr2_checkBox, 7, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 4, 1, 1)
        self.mpldoubleSpinBox5 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox5.setMaximum(2.0)
        self.mpldoubleSpinBox5.setSingleStep(0.01)
        self.mpldoubleSpinBox5.setProperty("value", 1.25)
        self.mpldoubleSpinBox5.setObjectName(_fromUtf8("mpldoubleSpinBox5"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox5, 5, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.mpldoubleSpinBox9 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox9.setMaximum(2.0)
        self.mpldoubleSpinBox9.setSingleStep(0.01)
        self.mpldoubleSpinBox9.setProperty("value", 1.25)
        self.mpldoubleSpinBox9.setObjectName(_fromUtf8("mpldoubleSpinBox9"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox9, 5, 3, 1, 1)
        self.mplfdr2_cbtime_SpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mplfdr2_cbtime_SpinBox.setMaximum(1.0)
        self.mplfdr2_cbtime_SpinBox.setSingleStep(0.01)
        self.mplfdr2_cbtime_SpinBox.setProperty("value", 0.06)
        self.mplfdr2_cbtime_SpinBox.setObjectName(_fromUtf8("mplfdr2_cbtime_SpinBox"))
        self.gridLayout.addWidget(self.mplfdr2_cbtime_SpinBox, 9, 3, 1, 1)
        self.mpldoubleSpinBox2 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox2.setMinimum(0.05)
        self.mpldoubleSpinBox2.setMaximum(1.0)
        self.mpldoubleSpinBox2.setSingleStep(0.01)
        self.mpldoubleSpinBox2.setProperty("value", 0.3)
        self.mpldoubleSpinBox2.setObjectName(_fromUtf8("mpldoubleSpinBox2"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox2, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.curveComboBox_2 = QtGui.QComboBox(self.frame)
        self.curveComboBox_2.setEditable(False)
        self.curveComboBox_2.setObjectName(_fromUtf8("curveComboBox_2"))
        self.curveComboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.curveComboBox_2, 4, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.mpldoubleSpinBox10 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox10.setMinimum(0.05)
        self.mpldoubleSpinBox10.setMaximum(1.0)
        self.mpldoubleSpinBox10.setSingleStep(0.01)
        self.mpldoubleSpinBox10.setProperty("value", 0.2)
        self.mpldoubleSpinBox10.setObjectName(_fromUtf8("mpldoubleSpinBox10"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox10, 2, 3, 1, 1)
        self.curveComboBox_3 = QtGui.QComboBox(self.frame)
        self.curveComboBox_3.setEditable(False)
        self.curveComboBox_3.setObjectName(_fromUtf8("curveComboBox_3"))
        self.curveComboBox_3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.curveComboBox_3, 4, 3, 1, 1)
        self.mpldoubleSpinBox4 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox4.setMaximum(2.0)
        self.mpldoubleSpinBox4.setSingleStep(0.01)
        self.mpldoubleSpinBox4.setProperty("value", 1.25)
        self.mpldoubleSpinBox4.setObjectName(_fromUtf8("mpldoubleSpinBox4"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox4, 5, 1, 1, 1)
        self.mplfdr1_checkBox = QtGui.QCheckBox(self.frame)
        self.mplfdr1_checkBox.setObjectName(_fromUtf8("mplfdr1_checkBox"))
        self.gridLayout.addWidget(self.mplfdr1_checkBox, 7, 2, 1, 1)
        self.mplinc_cbtime_SpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mplinc_cbtime_SpinBox.setMaximum(1.0)
        self.mplinc_cbtime_SpinBox.setSingleStep(0.01)
        self.mplinc_cbtime_SpinBox.setProperty("value", 0.06)
        self.mplinc_cbtime_SpinBox.setObjectName(_fromUtf8("mplinc_cbtime_SpinBox"))
        self.gridLayout.addWidget(self.mplinc_cbtime_SpinBox, 9, 1, 1, 1)
        self.mpldoubleSpinBox3 = QtGui.QDoubleSpinBox(self.frame)
        self.mpldoubleSpinBox3.setMinimum(0.05)
        self.mpldoubleSpinBox3.setMaximum(1.0)
        self.mpldoubleSpinBox3.setSingleStep(0.01)
        self.mpldoubleSpinBox3.setProperty("value", 0.2)
        self.mpldoubleSpinBox3.setObjectName(_fromUtf8("mpldoubleSpinBox3"))
        self.gridLayout.addWidget(self.mpldoubleSpinBox3, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.mplfdr1_highset_spinBox = QtGui.QDoubleSpinBox(self.frame)
        self.mplfdr1_highset_spinBox.setMinimum(2.0)
        self.mplfdr1_highset_spinBox.setMaximum(30.0)
        self.mplfdr1_highset_spinBox.setProperty("value", 10.0)
        self.mplfdr1_highset_spinBox.setObjectName(_fromUtf8("mplfdr1_highset_spinBox"))
        self.gridLayout.addWidget(self.mplfdr1_highset_spinBox, 6, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setProperty("value", 40)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout.addWidget(self.horizontalSlider, 7, 4, 1, 1)
        self.mplpushButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplpushButton.sizePolicy().hasHeightForWidth())
        self.mplpushButton.setSizePolicy(sizePolicy)
        self.mplpushButton.setObjectName(_fromUtf8("mplpushButton"))
        self.gridLayout.addWidget(self.mplpushButton, 9, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.mplcentralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_6 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_6.sizePolicy().hasHeightForWidth())
        self.tab_6.setSizePolicy(sizePolicy)
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.tab_6)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_9.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.widget4svg = widget4svg(self.frame_2)
        self.widget4svg.setObjectName(_fromUtf8("widget4svg"))
        self.widget4svg_2 = widget4svg(self.widget4svg)
        self.widget4svg_2.setGeometry(QtCore.QRect(10, 10, 391, 221))
        self.widget4svg_2.setObjectName(_fromUtf8("widget4svg_2"))
        self.gridLayout_9.addWidget(self.widget4svg, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_6, _fromUtf8("Circuit Diagram"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_9 = QtGui.QFrame(self.tab)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.mpl_1 = MplWidget(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_1.sizePolicy().hasHeightForWidth())
        self.mpl_1.setSizePolicy(sizePolicy)
        self.mpl_1.setMinimumSize(QtCore.QSize(0, 0))
        self.mpl_1.setObjectName(_fromUtf8("mpl_1"))
        self.gridLayout_5.addWidget(self.mpl_1, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_14 = QtGui.QLabel(self.frame_9)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox.setProperty("value", 35.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.verticalLayout_3.addWidget(self.doubleSpinBox)
        self.dial = QtGui.QDial(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial.sizePolicy().hasHeightForWidth())
        self.dial.setSizePolicy(sizePolicy)
        self.dial.setMaximumSize(QtCore.QSize(100, 100))
        self.dial.setMinimum(30)
        self.dial.setMaximum(90)
        self.dial.setSingleStep(5)
        self.dial.setPageStep(5)
        self.dial.setNotchTarget(10.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.verticalLayout_3.addWidget(self.dial)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_8 = QtGui.QFrame(self.tab_1)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.mpl_2 = MplWidget(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_2.sizePolicy().hasHeightForWidth())
        self.mpl_2.setSizePolicy(sizePolicy)
        self.mpl_2.setObjectName(_fromUtf8("mpl_2"))
        self.gridLayout_4.addWidget(self.mpl_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_6 = QtGui.QFrame(self.tab_3)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.mpl_5 = MplWidget(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_5.sizePolicy().hasHeightForWidth())
        self.mpl_5.setSizePolicy(sizePolicy)
        self.mpl_5.setMinimumSize(QtCore.QSize(50, 0))
        self.mpl_5.setObjectName(_fromUtf8("mpl_5"))
        self.gridLayout_15.addWidget(self.mpl_5, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.tab_3)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.mpl_11 = MplWidget(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_11.sizePolicy().hasHeightForWidth())
        self.mpl_11.setSizePolicy(sizePolicy)
        self.mpl_11.setMinimumSize(QtCore.QSize(50, 0))
        self.mpl_11.setObjectName(_fromUtf8("mpl_11"))
        self.gridLayout_16.addWidget(self.mpl_11, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_4.sizePolicy().hasHeightForWidth())
        self.tab_4.setSizePolicy(sizePolicy)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_4 = QtGui.QFrame(self.tab_4)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.mpl_6 = MplWidget(self.frame_4)
        self.mpl_6.setObjectName(_fromUtf8("mpl_6"))
        self.gridLayout_14.addWidget(self.mpl_6, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.tab_4)
        self.frame_5.setEnabled(True)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mpl_8 = MplWidget(self.frame_5)
        self.mpl_8.setObjectName(_fromUtf8("mpl_8"))
        self.gridLayout_2.addWidget(self.mpl_8, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_5.sizePolicy().hasHeightForWidth())
        self.tab_5.setSizePolicy(sizePolicy)
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_3 = QtGui.QFrame(self.tab_5)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mpl_7 = MplWidget(self.frame_3)
        self.mpl_7.setObjectName(_fromUtf8("mpl_7"))
        self.gridLayout_7.addWidget(self.mpl_7, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_13 = QtGui.QFrame(self.tab_5)
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_13)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.mpl_9 = MplWidget(self.frame_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_9.sizePolicy().hasHeightForWidth())
        self.mpl_9.setSizePolicy(sizePolicy)
        self.mpl_9.setObjectName(_fromUtf8("mpl_9"))
        self.gridLayout_11.addWidget(self.mpl_9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_13, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.frame_14 = QtGui.QFrame(self.tab_7)
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_14)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.mplwidget = MplWidget(self.frame_14)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.gridLayout_12.addWidget(self.mplwidget, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame_12 = QtGui.QFrame(self.tab_10)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.mpl_12 = MplWidget(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_12.sizePolicy().hasHeightForWidth())
        self.mpl_12.setSizePolicy(sizePolicy)
        self.mpl_12.setMinimumSize(QtCore.QSize(0, 0))
        self.mpl_12.setObjectName(_fromUtf8("mpl_12"))
        self.gridLayout_17.addWidget(self.mpl_12, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.frame_11 = QtGui.QFrame(self.tab_10)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.mpl_3 = MplWidget(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_3.sizePolicy().hasHeightForWidth())
        self.mpl_3.setSizePolicy(sizePolicy)
        self.mpl_3.setMinimumSize(QtCore.QSize(0, 0))
        self.mpl_3.setObjectName(_fromUtf8("mpl_3"))
        self.gridLayout_18.addWidget(self.mpl_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.frame_10 = QtGui.QFrame(self.tab_10)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.mpl_4 = MplWidget(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_4.sizePolicy().hasHeightForWidth())
        self.mpl_4.setSizePolicy(sizePolicy)
        self.mpl_4.setMinimumSize(QtCore.QSize(0, 0))
        self.mpl_4.setObjectName(_fromUtf8("mpl_4"))
        self.gridLayout_19.addWidget(self.mpl_4, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.webView = QtWebKit.QWebView(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("http://wiki.tesla.local/index.php/Sequential_Clearance")))
        self.webView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout_6.addWidget(self.webView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget, 2, 0, 1, 1)
        MplMainWindow.setCentralWidget(self.mplcentralwidget)
        self.menubar = QtGui.QMenuBar(MplMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MplMainWindow.setMenuBar(self.menubar)
        self.mplactionQuit = QtGui.QAction(MplMainWindow)
        self.mplactionQuit.setObjectName(_fromUtf8("mplactionQuit"))
        self.mplactionOpen = QtGui.QAction(MplMainWindow)
        self.mplactionOpen.setObjectName(_fromUtf8("mplactionOpen"))
        self.actionSave = QtGui.QAction(MplMainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(MplMainWindow)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.menuFile.addAction(self.mplactionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.mplactionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_6.setBuddy(self.mpldoubleSpinBox2)
        self.label_4.setBuddy(self.mpldoubleSpinBox6)
        self.label_3.setBuddy(self.mpldoubleSpinBox)
        self.label_11.setBuddy(self.curveComboBox_1)
        self.label_5.setBuddy(self.mpldoubleSpinBox4)
        self.label_10.setBuddy(self.mplinc_cbtime_SpinBox)
        self.label_9.setBuddy(self.mplinc_highset_SpinBox)

        self.retranslateUi(MplMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.curveComboBox_2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox3, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox4, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox2, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox5, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox6, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox7, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplspinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox8, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox9, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mpldoubleSpinBox10, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplfdr2_cbtime_SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplfdr1_cbtime_SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplinc_cbtime_SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplfdr2_highset_SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplfdr1_highset_spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplinc_highset_SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplfdr2_checkBox, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplfdr1_checkBox, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mplpushButton.click)
        QtCore.QObject.connect(self.mplinc_checkBox, QtCore.SIGNAL(_fromUtf8("clicked()")), self.mplpushButton.click)
        QtCore.QObject.connect(self.curveComboBox_1, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.curveComboBox_3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.mplpushButton.click)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), self.mplpushButton.click)
        QtCore.QObject.connect(self.dial, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), self.mplpushButton.click)
        QtCore.QMetaObject.connectSlotsByName(MplMainWindow)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox6, self.mpldoubleSpinBox2)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox2, self.curveComboBox_1)
        MplMainWindow.setTabOrder(self.curveComboBox_1, self.mpldoubleSpinBox4)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox4, self.mplinc_highset_SpinBox)
        MplMainWindow.setTabOrder(self.mplinc_highset_SpinBox, self.mplinc_checkBox)
        MplMainWindow.setTabOrder(self.mplinc_checkBox, self.mplinc_cbtime_SpinBox)
        MplMainWindow.setTabOrder(self.mplinc_cbtime_SpinBox, self.mpldoubleSpinBox7)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox7, self.mpldoubleSpinBox3)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox3, self.curveComboBox_2)
        MplMainWindow.setTabOrder(self.curveComboBox_2, self.mpldoubleSpinBox5)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox5, self.mplfdr1_highset_spinBox)
        MplMainWindow.setTabOrder(self.mplfdr1_highset_spinBox, self.mplfdr1_checkBox)
        MplMainWindow.setTabOrder(self.mplfdr1_checkBox, self.mplfdr1_cbtime_SpinBox)
        MplMainWindow.setTabOrder(self.mplfdr1_cbtime_SpinBox, self.mpldoubleSpinBox8)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox8, self.mpldoubleSpinBox10)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox10, self.curveComboBox_3)
        MplMainWindow.setTabOrder(self.curveComboBox_3, self.mpldoubleSpinBox9)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox9, self.mplfdr2_highset_SpinBox)
        MplMainWindow.setTabOrder(self.mplfdr2_highset_SpinBox, self.mplfdr2_checkBox)
        MplMainWindow.setTabOrder(self.mplfdr2_checkBox, self.mplfdr2_cbtime_SpinBox)
        MplMainWindow.setTabOrder(self.mplfdr2_cbtime_SpinBox, self.mplspinBox)
        MplMainWindow.setTabOrder(self.mplspinBox, self.mpldoubleSpinBox)
        MplMainWindow.setTabOrder(self.mpldoubleSpinBox, self.mplpushButton)
        MplMainWindow.setTabOrder(self.mplpushButton, self.tabWidget)
        MplMainWindow.setTabOrder(self.tabWidget, self.webView)

    def retranslateUi(self, MplMainWindow):
        MplMainWindow.setWindowTitle(QtGui.QApplication.translate("MplMainWindow", "Sequential Clearance 11kV System", None, QtGui.QApplication.UnicodeUTF8))
        self.mplinc_highset_SpinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Highset Pickup", None, QtGui.QApplication.UnicodeUTF8))
        self.mplinc_checkBox.setText(QtGui.QApplication.translate("MplMainWindow", "Highset Y/N", None, QtGui.QApplication.UnicodeUTF8))
        self.curveComboBox_1.setItemText(0, QtGui.QApplication.translate("MplMainWindow", "NI", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox6.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Incomer CT Primary Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox6.setSuffix(QtGui.QApplication.translate("MplMainWindow", "/1", None, QtGui.QApplication.UnicodeUTF8))
        self.mplfdr1_cbtime_SpinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "opening time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MplMainWindow", "Time Multiplier", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox7.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Feeder CT Primary Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox7.setSuffix(QtGui.QApplication.translate("MplMainWindow", "/1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MplMainWindow", "CT Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Zloop is the cable or overhead circuit between the two feeders\n"
"Zsource in this instance is the transformer impedance", None, QtGui.QApplication.UnicodeUTF8))
        self.mplfdr2_highset_SpinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Highset Pickup", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MplMainWindow", "Incomer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MplMainWindow", "Feeder 1", None, QtGui.QApplication.UnicodeUTF8))
        self.mplspinBox.setSuffix(QtGui.QApplication.translate("MplMainWindow", " percent", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox8.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Feeder CT Primary Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox8.setSuffix(QtGui.QApplication.translate("MplMainWindow", "/1", None, QtGui.QApplication.UnicodeUTF8))
        self.mplfdr2_checkBox.setText(QtGui.QApplication.translate("MplMainWindow", "Highset Y/N", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MplMainWindow", "Zloop to Zsource ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox5.setToolTip(QtGui.QApplication.translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Pickup</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MplMainWindow", "Curve Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MplMainWindow", "Pickup", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox9.setToolTip(QtGui.QApplication.translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Pickup</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.mplfdr2_cbtime_SpinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "opening time", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox2.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Incomer Multiplier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MplMainWindow", "Breaker Opening Time", None, QtGui.QApplication.UnicodeUTF8))
        self.curveComboBox_2.setItemText(0, QtGui.QApplication.translate("MplMainWindow", "NI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MplMainWindow", "Tx Impedance 20MVA single unit", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox10.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Feeder Multiplier", None, QtGui.QApplication.UnicodeUTF8))
        self.curveComboBox_3.setItemText(0, QtGui.QApplication.translate("MplMainWindow", "NI", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox4.setToolTip(QtGui.QApplication.translate("MplMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Pickup</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.mplfdr1_checkBox.setText(QtGui.QApplication.translate("MplMainWindow", "Highset Y/N", None, QtGui.QApplication.UnicodeUTF8))
        self.mplinc_cbtime_SpinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "opening time", None, QtGui.QApplication.UnicodeUTF8))
        self.mpldoubleSpinBox3.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Feeder Multiplier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MplMainWindow", "High Set Pickup", None, QtGui.QApplication.UnicodeUTF8))
        self.mplfdr1_highset_spinBox.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Highset Pickup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MplMainWindow", "Feeder 2", None, QtGui.QApplication.UnicodeUTF8))
        self.mplpushButton.setText(QtGui.QApplication.translate("MplMainWindow", "Re-calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(QtGui.QApplication.translate("MplMainWindow", "<html><head/><body><p>Matplotlib</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_1.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MplMainWindow", "Line Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox.setSuffix(QtGui.QApplication.translate("MplMainWindow", "deg", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MplMainWindow", "Margin Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_2.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MplMainWindow", "Margin Plot Detail", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_5.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_11.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MplMainWindow", "Incomer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MplMainWindow", "Feeder1/2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MplMainWindow", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MplMainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_12.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_3.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.mpl_4.setToolTip(QtGui.QApplication.translate("MplMainWindow", "Matplotlib", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QtGui.QApplication.translate("MplMainWindow", "ITOC Curves", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MplMainWindow", "Tesla Wiki", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MplMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionQuit.setText(QtGui.QApplication.translate("MplMainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.mplactionOpen.setText(QtGui.QApplication.translate("MplMainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MplMainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MplMainWindow", "SaveAs", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
from widget4svg import widget4svg
from mplwidget import MplWidget
import sequential_clearance_resources_rc
import sequential_clearance_resources2_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MplMainWindow = QtGui.QMainWindow()
    ui = Ui_MplMainWindow()
    ui.setupUi(MplMainWindow)
    MplMainWindow.show()
    sys.exit(app.exec_())

